CFLAGS = -Wall -g -std=c++11

test: test_extrinsicminpq.cpp ExtrinsicMinPQ.h ExtrinsicMinPQ.cpp
	g++ $(CFLAGS) -o test_extrinsicminpq test_extrinsicminpq.cpp

clean:
	rm test_extrinsicminpq *.o -f *~
